pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                dir('shorturl') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
    }
}